### ISSUE TITLE
PID should avoid derivative kick

### ISSUE THREAD

**Issue by gelanchez** [bitcraze/crazyflie-firmware#1336]
The code for the PID calculation works out the derivative term by differentiating the error, which causes a derivative kick when the setpoint changes. This issue can be avoided by using the derivative of the measured value, since that's equal to the derivate of the error when the setpoint is constant.

`float deriv = -(measured - pid->prevMeasured) / pid->dt;`

**Comment by knmcguire** [comment]
Hi! Very sorry for the late reply. As you noticed our support has been slow because of the holidays.

That is a very good point, [The principle of a PID controller ](https://en.wikipedia.org/wiki/Proportional%E2%80%93integral%E2%80%93derivative_controller#Fundamental_operation)is to have the derivative of the error but I can definitely get that in practice this will cause problems. 

Let's communicate further in the PR about the implications.
