### ISSUE TITLE
Add description field to all LOG and PARAM variables

### ISSUE THREAD

**Issue by tobbeanton** [bitcraze/crazyflie-firmware#148]
As many wonder what the LOG variables and PARAMs really mean I suggest adding a description to them. We could e.g. go the doxygen way or maybe even add that to the macro so it could be fetched from the cfclient and displayed there.

**Comment by krichardsson** [comment]
One solution would be to add a description as a fourth parameter to the PARAM_ADD and LOG_ADD. We add access to the strings through the memory sub system by adding two new memory types and assign each parameter and log entry a memory area based on its id in the TOC. The address could for instance be chosen as id * 1024 or similar.
This have no impact on performance since the strings are only transferred when needed and it does not breaks current implementations.
