### ISSUE TITLE
Wrong display of large hexa string (serial number)

### ISSUE THREAD

**Issue by sdalu** [bitcraze/crazyflie-firmware#256]
The `eprintf` function doesn't support print size settings, which is problematic for printing  number above 32bits, such as the MCU serial number or the dwm1000 mac address

For example MCU serial number printed is (in my case) only 22 char (88bits) instead of 24 char (96bits)
~~~
SYS: I am 0x32313338323551121D0030 and I have 1024KB of flash!
~~~

**Comment by ataffanel** [comment]
This is right, it is due to the fact that we use an home-made printf that does not have all functionalities.

We could add the size to printf or we could use printf from gcc. We have used printf fron the nano lib of GCC-ARM-EABI for the lps node with some success so I think we should drop eprintf and go for the gcc version.
