### ISSUE TITLE
Fail to compile Arch Linux

### ISSUE THREAD

**Issue by snyderth** [bitcraze/crazyflie-firmware#340]
I am trying to build the firmware on arch and every time I `make compile` or `make build` it returns the following error:
`In file included from **src/modules/src/crtp_commander_generic.c:35:
/usr/arm-none-eabi/include/math.h:133:12: error:** expected identifier or '(' before '**double**'
extern int isnan (double);`
'**src/utils/interface/num.h:41:28: error:** expected ')' before '?' token
#define isnan(n) ((n !- n) ? 1: 0)`

I just updated my local copy today. I'm building with config.mk options:
`PLATFORM=CF2
ESTIMATOR=kalman
LPS_TDOA_ENABLE=1
CLOAD=1`

**Comment by snyderth** [comment]
Compiling with toolbelt works

**Comment by ataffanel** [comment]
Good that it worked with the toolbelt/docker.

The original problem was most likely caused by a wrong version of GCC, the Crazyflie firmware should be compiled with [gcc-arm-embedded](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm). If you add it in your path you will be able to compile crazyflie-firmware directly from arch.
