### ISSUE TITLE
Charging LED pattern not shown at startup

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-firmware#364]
If the Crazyflie starts while plugged to USB power, the M3 LED will not blink to indicates that the battery is charging. Though, if the USB power is connected while the Crazyflie is running, the M3 LED displays the charging state accurately.

The charging state should be indicated on the M3 LED at all time, even just after startup.

**Comment by ntamas** [comment]
@ataffanel Did this commit solve the problem for you? On my CF, the charging LED pattern is still not shown at startup when the USB is plugged in before the Crazyflie is turned on. Some debugging revealed that the syslink message coming from the nRF chip is claiming that the battery is not charging, so the STM32 is right in not showing the "charging" light pattern. The issue is likely to be on the nRF side. (Both firmwares are at the latest master revision).
