### ISSUE TITLE
[Idea] 2 lighthouse decks to fly over the anchors

### ISSUE THREAD

**Issue by benkuper** [bitcraze/crazyflie-firmware#440]
Currently the lighthouse decks have only horizontal sensors, would it be imaginable to also have a lighthouse deck under the drone to be able to have better coverage ?
The firmware would need to be able to handle 2 decks of the same type, and the pins may be inversed, but worth thinking about it maybe :)

**Comment by ataffanel** [comment]
With some firmware modification and custom soldering it would be possible to use the current deck above and under the Crazyflie. The modification would not be very obvious, but it would technically be possible (the second deck UART can be cabled to the Crazyflie other UART). The easiest I assume would be to make another deck driver for the bottom deck that bootloads over UART instead of I2C.

If you are interested in testing this idea the best would be to start a thread on the Bicraze forum so that we can talk a bit more about the electronic and firmware modification needed.

Since it will require so much custom hardware hacking, I do not think this is something we can add to master. Though this is a good thing to keep in mind for the next revision of the Lighthouse deck.
