### ISSUE TITLE
Params/log for Radio connectivity?

### ISSUE THREAD

**Issue by NicksonYap** [bitcraze/crazyflie-firmware#459]
Hi Bitcraze team ,

Using: 

```
rssiid = logGetVarId("radio", "rssi");
rssi = logGetFloat(rssiid);
```

We can get the RSSI, however, when disconnected, the RSSI stops changing, and does not indicate that connection was broken.

How can we obtain the state of the connectivity from CF?

Thanks!

**Comment by ataffanel** [comment]
Hi,
A while ago we have added a connection state to the radio link: https://github.com/bitcraze/crazyflie-firmware/issues/428. Since there is no real "connection" in the Crazyflie communication, this is just a timeout that assumes the link is disconnected after 1 seconds.

There is no log setup for this but it could be added.

**Comment by NicksonYap** [comment]
Merged in: https://github.com/bitcraze/crazyflie-firmware/pull/466
