### ISSUE TITLE
complementary estimator

### ISSUE THREAD

**Issue by mandelyoni** [bitcraze/crazyflie-firmware#519]
Hi,

Is the complementary estimator suppose to work with the flow deck?

Thanks, Yoni

**Comment by ataffanel** [comment]
No, when the flow-deck is detected and initialized the Kalman filter is enabled.

The complementary filter only works with the IMU and with the z-ranger deck V1.

**Comment by mandelyoni** [comment]
Hi,

Have you lately checked the complementary filter with the IMU and with the z-ranger deck V1?
We're having a hard time making it work.

Thanks,  Yoni

**Comment by ataffanel** [comment]
We have not changed anything that should break the z-ranger deck V1. I just tested with the latest Master and a Z-ranger V1, it still works fine. There is a little bit of Z oscillation compared to the Kalman estimator but it is not much.

Since the questions have been answered I am closing this ticket. Do not hesitate to re-open it or open a new one if you have further questions.
