### ISSUE TITLE
Problems in kalman estimator using LPS and Flow deck at the same time

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-firmware#523]
There seems to be some sort of clash in the kalman filter when using a Flow deck and LPS at the same time.
Reported symptoms is that it works for a while but suddenly flips.

**Comment by knmcguire** [comment]
Currently there have been improvements to the flowdeck implementation within the kalmanfilter in #608. The standard deviation of the flow measurements was way too small and therefore if the flowdeck was not able to detect flow, it will crash since it trusted it too much. 

Now with the new implementation, I was able to fly in and out of the lps system with the flowdeck with no problem at all. However, if the lps system is turned on after the crazyflie is started up, or the crazyflie flies away from the LPS system with the flowdeck and comes back with a bit of drift, the position estimate will jump  to a different position (relative vs global position estimation) so that is something to be aware of. As long as you are flying with velocity commands this should be all okay :) I will close this issue.

BTW. I was flying with TDOA2 and TDOA3. The issue between the flowdeck and TWR is looked at in #368, but that is a different matter.
