### ISSUE TITLE
Memory issue of the micro SDcard deck

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-firmware#561]
Watchdog timout is triggered with the SD card deck in combination with other expansion decks. The memory capacity is getting low.

Issue found in this forum post: https://forum.bitcraze.io/viewtopic.php?f=5&t=4186&p=19075#p19075

**Comment by tobbeanton** [comment]
The memory issue was fixed as part of implementing support for an alternative choice of using SPI3 so the sd-card deck can be used together with loco-deck and flow deck.

To have the sd-card on SPI3 the SD-deck needs to be patched or a sd-card adapter breakout can be used. Compile the firmware with "CFLAGS += -DUSDDECK_USE_ALT_PINS_AND_SPI" in config.mk.

A side effect is that the led-ring will not work due to DMA conflict with SPI3.
