### ISSUE TITLE
Freeze Crazyflie-Bolt with Lighthouse enable

### ISSUE THREAD

**Issue by poritech** [bitcraze/crazyflie-firmware#795]
Hello!

I had a problem with Crazyflie-Bolt when I flash latest firmware to it with making some flags on.
I have 3 Crazyflie-Bolt and all of them freeze, so I don't think it's a hardware problem.

I think problem is caused by **"CFLAGS += -DDISABLE_LIGHTHOUSE_DRIVER=0"**, because the same problem occurs with **"CFLAGS += -DDISABLE_LIGHTHOUSE_DRIVER=0"** alone.
Is the way to enable Lighthouse wrong?

### Steps to Reproduce
1. Add some flags to config.mk.
```
PLATFORM=cf2
CFLAGS += -DDECK_FORCE=bcLedRing
CFLAGS += -DDISABLE_LIGHTHOUSE_DRIVER=0
```
2. Build and flash firmware to the Crazyflie-Bolt.
3. Crazyflie-Bolt freezed like following video.
https://drive.google.com/file/d/1KbiBc3_lPiP-0fMhYyzZ-I60eR73L5bj/view?usp=sharing
The LED animation has stopped, indicating that the Crazyflie-Bolt is frozen

### Context (Environment):
- OS: Ubuntu 18.04
- crazyflie-firmware repository version: 2021.03

**Comment by krichardsson** [comment]
Hi!

The `DISABLE_LIGHTHOUSE_DRIVER` flag is not used any more (it was removed a few moths ago) and should have no effect on the 2021.03 code. You don't need to change anything in the firmware in order to enable lighthouse support, it is already there. You can follow this guide https://www.bitcraze.io/documentation/tutorials/getting-started-with-lighthouse/ to get started. 

Make sure to follow the instructions here https://www.bitcraze.io/documentation/repository/crazyflie-clients-python/master/userguides/userguide_client/#firmware-upgrade to ensure that the binary in the lighthouse deck is upgraded.

I don't see why setting the `DISABLE_LIGHTHOUSE_DRIVER` flag would freeze the bolt so there is something weird going on though. Have you tried to flash the bolt with the official 2021.03 release, without any modifications? That is probably a good starting point.

I also want to check if you have read recently about using the DISABLE_LIGHTHOUSE_DRIVER flag, and where. We are working on upgrading our documentation and want to find any pages we have missed to update. 

Thanks!

**Comment by poritech** [comment]
Hi krichardsson!
Thanks for your reply.

The lighthouse deck was using the updated by crazyflie-client.

I flash the bolt with the official 2021.03 release, without any modifications. And I found 3 things.
1. Bolt freeze with mounting lighthouse deck.
2. Bolt does not freeze without lighthouse deck.
3. Crazyflie 2.1 does not freeze with mounting lighthouse deck.
4. Bolt does not freeze when I flash the bolt with the official 2021.03 release from crazyflie-client.

Regards,

**Comment by krichardsson** [comment]
Hi!

So if I understand correctly the Bolt + Lighthouse deck works with the official 2021.03 release but not when you compile your own? If this is the case the compiler might be the problem, we have seen this in other cases as well. The official release is built with version 9-2020-q2-update of https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

Which version do you use?

**Comment by ntamas** [comment]
Indeed it seems to be a compiler problem; we have been hit by this as well.

Some additional information:

* Building the 2021.03 tag with `gcc` 7.2.1 installed from Homebrew on macOS (`gcc-arm-none-eabi-74`, version `20171218`) causes a crash at startup with the following assertion failure: `SYS: Assert failed at .//src/utils/interface/cf_math.h:78`.
* The stock firmware works perfectly fine for the same quad.

I'll try with a few other `gcc` versions.

**Comment by ntamas** [comment]
Also, it has nothing to do with the Lighthouse deck; we have an LED ring and the UWB deck installed on this quad.

**Comment by krichardsson** [comment]
Thanks @ntamas for the version list!

If I remember correctly there was something that changed related to alignment in packed structs or similar, not sure. Anyway to be sure to build with the correct compiler, one can use the toolbelt (https://github.com/bitcraze/toolbelt) to build.

**Comment by poritech** [comment]
Thanks @ntamas and @krichardsson!

I was using an older version of the compiler.
I used toolbelt and it worked perfectly!

**Comment by krichardsson** [comment]
Great! I'll close the issue
