### ISSUE TITLE
Kbuild: Add functionality to flash a specific Crazyflie

### ISSUE THREAD

**Issue by jonasdn** [bitcraze/crazyflie-firmware#948]
In the previous system it was possible to add a line to your config.mk file that warm booted a crazyflie based on the radio channel/address and flashed to it when using `make cload`. This does not work in the new KBuild setup but I think we should re-add it somehow. 

This feature is very useful in a class room environment for instance, to avoid concurrent cold boot/flashing by multiple students. If two students flash at the same time, the images will be corrupted and cause general confusion. With the warm boot feature multiple users can flash at the same time. 

This feature could be added to KBuild, but there are possibly other ways that are better. One option would be to use an environment variable instead, perhaps the same that is used in the python examples (CFLIB_URI="radio://0/30/2M/E7E7E7E7E7")?

**Comment by knmcguire** [comment]
Currently the instructions say we should now use CLOAD_CMDS  as an environment variable (see these [old instructions](https://github.com/bitcraze/crazyflie-firmware/blob/master/docs/building-and-flashing/build.md#automatically-enter-bootloader-mode), instead of config.mk, which should be good enough for now. 

What we could do is to say is that people can add these to their bashrc on ubuntu, but this need to be tested if this works on WSL at all.

**Comment by knmcguire** [comment]
it does not seem that anybody seems to need this specifically, so I'll close it.
